### ISSUE TITLE
createChatInviteLink   Count the number of invitees

### ISSUE THREAD

**Issue by devghb** [yagop/node-telegram-bot-api#1031]

**Comment by danielperez9430** [comment]
The count of the invites is doing in the telegram back end side and is not return in the Telegram Bot API.

Example case:
- 1 User enter with this link limit to 2 user (1/2)
- Other user enter with this link (now 0/2 users can enter)
- One of this users that joins with your limit invite link exit the group (Now the link allow to 1 user to enter, because the count change from 0/2 to 1/2)

The best is create a link also with expiration time or revoke it when the user is join

**Comment by devghb** [comment]
The link generated by createChatInviteLink ，not chat invite_link

**Comment by devghb** [comment]
> The count of the invites is doing in the telegram back end side and is not return in the Telegram Bot API.
> 
> Example case:
> 
>     * 1 User enter with this link limit to 2 user (1/2)
> 
>     * Other user enter with this link (now 0/2 users can enter)
> 
>     * One of this users that joins with your limit invite link exit the group (Now the link allow to 1 user to enter, because the count change from 0/2 to 1/2)
> 
> 
> The best is create a link also with expiration time or revoke it when the user is join



How to count the number of invitees with robot

**Comment by danielperez9430** [comment]
> > The count of the invites is doing in the telegram back end side and is not return in the Telegram Bot API.
> > Example case:
> > ```
> > * 1 User enter with this link limit to 2 user (1/2)
> > 
> > * Other user enter with this link (now 0/2 users can enter)
> > 
> > * One of this users that joins with your limit invite link exit the group (Now the link allow to 1 user to enter, because the count change from 0/2 to 1/2)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The best is create a link also with expiration time or revoke it when the user is join
> 
> How to count the number of invitees with robot

At less you use a db for store it, can be complex to know
