### ISSUE TITLE
Launching web app from inline mode

### ISSUE THREAD

**Issue by Sladrus** [yagop/node-telegram-bot-api#1091]
![image](https://github.com/yagop/node-telegram-bot-api/assets/47065712/97bb691b-da20-4c6a-a849-da4ca3abc0a4)

Hello, how i can launching web app from inline mode? need that button "make custom order"

**Comment by raskyer** [comment]
This depends on support of Telegram's version **6.7** and this library supports up to **6.3**.

Even Telegraf is stuck to **6.5** : https://github.com/telegraf/telegraf/issues/1835
So for now, no support until **6.7** is reached.

The only solution if you really need it is to use the python library (which has a way bigger community).

**Comment by danielperez9430** [comment]
You don't need to update the library for use the button in the answerInlineQuery, because is a optional param and this library support this optional params out the box.

InlineQueryResultsButton: A JSON-serialized object describing a button to be shown above inline query results 

Example: 
answerInlineQuery(inline_query_id, results, { button: JSON.parse({ `InlineQueryResultsButton`
 }) })

**Comment by Sladrus** [comment]
There is a problem that everything opens on a PC and Android, but on an iPhone the button is simply clicked and nothing happens

**Comment by KnorpelSenf** [comment]
> The only solution if you really need it is to use the python library (which has a way bigger community).

This is just wrong, the python community may be large but they don't exactly release faster updates than some JS libs. I know it because [I wrote one](https://git.io/grammyjs), and we almost always ship an update less than 24 hours after the Bot API release. For example, PTB was more than two weeks late.

**Comment by raskyer** [comment]
> > The only solution if you really need it is to use the python library (which has a way bigger community).
> 
> This is just wrong, the python community may be large but they don't exactly release faster updates than some JS libs. I know it because [I wrote one](https://git.io/grammyjs), and we almost always ship an update less than 24 hours after the Bot API release. For example, PTB was more than two weeks late.

I wasn't aware of this library. Great to see solutions for node community.

**Comment by danielperez9430** [comment]
The problem was more the 2 braking changes from Telegram the "createNewStickerSet" and "addStickerToSet". That required more work because need to change the way that the data was send. In other case the release can be do in the same date. If I have a little more time this weekend I maybe finish this last two things in the pull request https://github.com/yagop/node-telegram-bot-api/pull/1069
