### ISSUE TITLE
Initialize only with App Id and App Hash

### ISSUE THREAD

**Issue by pedroota** [yagop/node-telegram-bot-api#1096]
Hello everyone,

I hope you're doing well! I'm currently facing some challenges while trying to create a specific use case for a bot. The bot should be able to initialize with only the App Id and App Hash from a Telegram account. Once the code is initialized, it will prompt the user for their phone number and the code sent by Telegram. In some cases, it may also require the user's two-factor authentication password, if applicable.

I was wondering if there is a way to achieve this functionality. Any guidance or suggestions would be greatly appreciated.

Thank you all!

**Comment by danielperez9430** [comment]
Hi @pedroota 

I think you are confused. App Id and App hash is only for "MTProto API", no "Bot API".

MTProto -> Normal client API - like Telegram Android/ iOS... or Tdlib (you can also login with bot token because in the tdlib is used as part of the backend of the Telegram Bot API, but have a diferents limits to a normal account)

**Bot API** -> Is exclusive for bots only and is the target of this library.

If you want to create a userbot you need a library that works with MTProto (Tdlib, Madelineproto, Pyrogram....), and this allows you to login with a phone number
