### ISSUE TITLE
Way to run bot behind proxy

### ISSUE THREAD

**Issue by rjmunhoz** [yagop/node-telegram-bot-api#122]
I need to use the bot behind a corporate proxy.

I've tried to find where to put so I could make a pull request, but couldn't

**Comment by iiroj** [comment]
You need a web server that forwards messages to the Telegram Bot API in any case, so being behind is no problem as long as you control the proxy.

You can see an example in [this file](https://github.com/iiroj/pintbot/blob/master/server.js) of a server listening on 127.0.0.1:8443 and forwarding messages to this API (pintbot in my case).

Then (eg. Nginx) for your reverse proxy something like:
```
location /yourtelegrampath {
    proxy_pass http://127.0.0.1:8443;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
```

**Comment by rohmunhoz** [comment]
I'm actually using Long Polling, and the proxy won't let the requests go out without auth.
I've set up CNTLM and I'm able to make HTTP and HTTPS requests if I can set the module to use my proxy, wich authenticates with the corporate one and redirects the request 
What I'm looking for, actually, is something like

`request.setProxy('http://127.0.0.1:1234');`

**Comment by GochoMugo** [comment]
v0.25.0 added the ability to pass [request options](https://github.com/yagop/node-telegram-bot-api#new-telegrambottoken-options). Therefore, you may do something like:

```js
const bot = new TelegramBot(token, {
  polling: true,
  request: {
    proxy: "http://127.0.0.1:1234",
  },
});
```

See [request's docs](https://github.com/request/request#requestoptions-callback) on more information on the proxy!

Otherwise, if you are using webhooks, please proceed to issue #253!

(PS: Join our [Telegram channel](https://telegram.me/node_telegram_bot_api) for updates)

**Comment by rjmunhoz** [comment]
Thanks so much!

**Comment by DiogoRNeves** [comment]
Hi guys! I'm using 

```
const bot = new TelegramBot(token, {
  polling: true,
  request: {
    proxy: "http://[user]:[pw]@127.0.0.1:1234",
  },
});
```

When I access the URL on the browser it works, so i know it is not blocked.

But it still fails... The string I used is the same i get from the command 

`npm config get proxy`

And npm works great.

Any thoughts?

**Comment by DiogoRNeves** [comment]
Just tested it on basic request an it works...

```
var request = require('request');
request({
		url: 'http://www.google.com',
        proxy: "http://[user]:[pw]@127.0.0.1:1234"
      } , function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log(body) // Show the HTML for the Google homepage.
  }
})
```

**Comment by GochoMugo** [comment]
We hope you are using the latest version i.e. v0.25.0!

**Comment by DiogoRNeves** [comment]
Yup!

```
$ npm list node-telegram-bot-api
pokefarmer-telegram-bot@0.0.1 C:\Users\scu007\Documents\PokeFarmerTelegramBot
`-- node-telegram-bot-api@0.25.0
```

**Comment by GochoMugo** [comment]
You read through the [Proxy Documentation](https://github.com/request/request#proxies)?

**Comment by DiogoRNeves** [comment]
Yup...

I think i figured it out... node-telegram-bot-api is not reaching the _request method. Here's the stack:

```
Unhandled rejection RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
    at new RequestError (*myPath*\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (*myPath*\node_modules\request-promise-core\lib\plumbing.js:87
:29)
    at Request.RP$callback [as _callback] (*myPath*\node_modules\request-promise-core\lib\plumb
ing.js:46:31)
    at self.callback (*myPath*\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (*myPath*\node_modules\request\request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

As far as I could see, node-telegram-bot-api is not even getting it's _request method (I inserted a console.log() there, it never came out...

**Comment by DiogoRNeves** [comment]
Just in case it helps anyone, I solved it by setting 

```
process.env.http_proxy="http://[user]:[pw]@127.0.0.1:1234"
process.env.https_proxy="http://[user]:[pw]@127.0.0.1:1234"
```

Since the request module always respects env variables, there's no need to set the request option anymore and it probably works with older versions of node-telegram-bot-api as well.

Also, one can skip hardcoding the proxy by using the env :-)

Thanks @GochoMugo for your replies!

**Comment by MRGando** [comment]
Guys i need to proxy my telegram bot, i have a server to connect, but node-telegram-bot-api returns error while trying to connect to the server, it's because the server needs username and password to connect, how can i set username and password in this package?

I wrote HOST and PORT but there is no parameter for username or password 🤦
