### ISSUE TITLE
Group messages not being received on 'message' ?

### ISSUE THREAD

**Issue by hems** [yagop/node-telegram-bot-api#190]
This is how i found this issue:

----
1 - created a bot
2 - added to the group ( i'm admin of the group )
3 - checked list of users on the group and saw "has no access to messages"
4 - set privacy to "disable"
5 - checked list of users on the group and saw "has access to messages"
5 - checked on 'message' callback, but it only work for private messages, group messages aren't being received here

----

Am i supposed to remove the bot and add to the group again?

Maybe group messages goes to onText instead of on 'message' ?

**Comment by GochoMugo** [comment]
This issue is related to an older one: https://github.com/yagop/node-telegram-bot-api/issues/174. Please see that issue for possible fixes. Should they work, please close this issue.

Also, **all** messages cause the bot to emit **message** event (see [src/telegram.js#L91](https://github.com/yagop/node-telegram-bot-api/blob/e0e5e9a7b0cbf823e008704b76d614e5da6e2922/src/telegram.js#L91)). If the message is **text**, the **text** event is emitted (see [src/telegram.js#L95](https://github.com/yagop/node-telegram-bot-api/blob/e0e5e9a7b0cbf823e008704b76d614e5da6e2922/src/telegram.js#L95)) and the `onText()` regexes are executed (see [src/telegram.js#L101](https://github.com/yagop/node-telegram-bot-api/blob/e0e5e9a7b0cbf823e008704b76d614e5da6e2922/src/telegram.js#L101)).

**Comment by hems** [comment]
removing the bot and adding again sorted the issue, thanks!
