### ISSUE TITLE
Way to multiple SendMessage in correct sequence

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#240]
There is a way to send multiple Message in rapid sequence without change their order?

For example
```
bot.SendMessage(chat_id, "1");
bot.SendMessage(chat_id, "2");
bot.SendMessage(chat_id, "3");
```

Sometimes print
321 or 312 or 132

But i need
123

Thanks a lot!

**Comment by yagop** [comment]
Haven't tested it, but something like:

```js
bot.SendMessage(chat_id, "1")
  .then(() => {
    return bot.SendMessage(chat_id, "2")
  })
  .then(() => {
    return bot.SendMessage(chat_id, "3")
  })
```

El vie., 16 dic. 2016 9:27, Edoardo Cortese <notifications@github.com>
escribió:

There is a way to send multiple Message in rapid sequence without change
their order?

For example

bot.SendMessage(chat_id, "1");
bot.SendMessage(chat_id, "2");
bot.SendMessage(chat_id, "3");

Sometimes print
321 or 312 or 132

But i need
123

Thanks a lot!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yagop/node-telegram-bot-api/issues/240>, or mute the
thread

**Comment by sidelux** [comment]
It works!

![image](https://cloud.githubusercontent.com/assets/18572941/21256782/9827467a-c374-11e6-91e3-c76a454c3a7e.png)
