### ISSUE TITLE
options.baseApiUrl not working

### ISSUE THREAD

**Issue by rjmunhoz** [yagop/node-telegram-bot-api#259]
I instantiated the bot like this, but it didn't use PWRTelegram's API URL.

```javascript
const bot = new TelegramBot(TELEGRAM_TOKEN, {
        webHook: {
            host: HOST
            , port: PORT
        }
        , onlyFirstMatch: true
        , baseApiUrl: 'https://api.pwrtelegram.xyz'
    });
```

Also, looking at the files on my node_modules, I couldn't find anywhere that option could be used.

Maybe I'm noobing here, but I'd really like to use PWRTelegram's API.

For instance, I know it's no being used because passing `@rmunhoz` as the chat_id didn't work as it would if using PWRTelegram

**Comment by GochoMugo** [comment]
Will be available in next release!

We should document on the right docs to use for the latest release!

**Comment by kamikazechaser** [comment]
@rjmunhoz Use [tgfancy](https://github.com/gochomugo/tgfancy] If you want to pass a username instead of a chat_id. This library provides a low level interface to the Telegram API, and such a feature may not be implemented on node-telegram-bot-api. Alternatively you can plug-in [tg-resolve](https://github.com/kamikazechaser/tg-fancy) into node-telegram-bot-api and use the resolution feature!

**Comment by rjmunhoz** [comment]
Thanks, @kamikazechaser! I'll certainly have look on those!

**Comment by GochoMugo** [comment]
`options.baseApiUrl` was added in **v0.26.0**
