### ISSUE TITLE
Capturing a text message in a  chat group?

### ISSUE THREAD

**Issue by icaroramiires** [yagop/node-telegram-bot-api#304]
Hello, I'm using the bot in a chat group, but it only interprets commands, I would like to capture other types of messages, such as for example text messages

**Comment by hosein2398** [comment]
Due to privacy of users bots have no access to users messages except some specific ones.
More information [here](https://core.telegram.org/bots#privacy-mode) and [here](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get).
Only way you can receive users messages in group is to set your bot as one of admins in the group.
And clearly you can only do that if you'r creator of the group or probably one of admins.

**Comment by icaroramiires** [comment]
Thank you @hosein2398  here it worked now! 👏
