### ISSUE TITLE
Promise on downloadFile

### ISSUE THREAD

**Issue by K3ler** [yagop/node-telegram-bot-api#35]
i don't understand, i try download file, but Promise dont contain filePath varible.
I use 

	bot.on('photo', function(msg) {

		var path = bot.downloadFile(msg.photo[msg.photo.length-1].file_id, "./public/img").filePath;
		console.log(path);
	});

but, i got 

{ _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _progressHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: undefined }

where i lose?

**Comment by yagop** [comment]
What `downloadFile` returns is a Promise created by [Bluebird](https://github.com/petkaantonov/bluebird).

A [Promise](https://promisesaplus.com/) is an `object` with a `then` method which parameter is the callback of the asynchronous action once is resolved.

What I mean is, you have to call `then` with your callback.

Eg:

```js
// I haven't tested this code, its based on what you write.
bot.on('photo', function(msg) {
  var photoId = msg.photo[msg.photo.length-1].file_id;
  var path = bot.downloadFile(photoId, "./public/img").then(function (path) {
    console.log(path);
  });
});
```

**Comment by K3ler** [comment]
oh, it`s works! I am noob in NodeJS, Thanks!

**Comment by yagop** [comment]
On NodeJS the I/O operations are asynchronous (like HTTP petitions or writing on a file), this is the best part of NodeJS without doubt. To execute a function after a an asynchronous action, a callback is provided. One way is passing the callback on the function parameters, but it turns out into a callback hell.

On `node-telegram-bot-api` Bluebird Promises are provided to simplify the development.
