### ISSUE TITLE
Games push a popup with the link instead of a game view

### ISSUE THREAD

**Issue by koso00** [yagop/node-telegram-bot-api#418]
When i create a game bot and i start it , a popup show me the link of the game instead of opening a webview like other games

**Comment by MCSH** [comment]
They have changed the api. You have to provide a query_callback_id and a url only.

The example uses the old library where you had to provide a text and a Boolean as well and that's why it doesn't work.

**Comment by joshrayman** [comment]
We came up against this problem yesterday - ended up using a quick hack. (changing the 'text' parameter in telegram.js:1052 for 'url' in the legacy format, because this doesn't accounted for the older syntax which had an object further along the query to specify a url)

But looking at that function you're supposed to give it an object instead of the three parameters like the old API/examples/code that you see online.

So it'd be sending answerCallbackQuery(obj)
`{
        callback_query_id: id,
        url: 'url',
}`

instead of answerCallbackQuery(id, url).

**Comment by GochoMugo** [comment]
This has been fixed. Thanks. :smile:

**Comment by rharkor** [comment]
Maybe late but I have the same problem
