### ISSUE TITLE
Q: Do webHook work on locale?

### ISSUE THREAD

**Issue by cawa-93** [yagop/node-telegram-bot-api#451]
I'm new to creating a bot and I have a few questions.
First of all, I will clarify that I'm going to place my bot on a hack. I'm using the jQuery clip to run on the local machine.
That for me it is not clear:
1. Do I understand correctly that your library can work in two modes (webHook and polling)?
2. webHook waiting while the telegram server reports about new message? And in the polling mode, does the library regularly check for updates?
3. I understand correctly that webHook mode will not work on the local machine and polling - yes? And I have to check the `NODE_ENV` to run your library in this or that mode.
```js
if (process.env.NODE_ENV === 'production') {
  const options = {
    webHook: {
      port: process.env.PORT
    }
  };
  const url = process.env.APP_URL || 'https://<app-name>.herokuapp.com:443';
  const bot = new TelegramBot(TOKEN, options);
  bot.setWebHook(`${url}/bot${TOKEN}`);
} else {
  const options = {
    polling: true
  };
  const bot = new TelegramBot(TOKEN, options);
}
```

**Comment by alexandercerutti** [comment]
The question behind this is one: how can I retrieve the updates?
There are two ways: webHook and polling.
Polling means that **your** application keeps asking to the server, whichever is its IP:PORT set.
WebHook, instead, requires a permanent HTTPS address with a valid certificate, to be reached by the Update supplier (i.e. Telegram Bot API). This address must be permanent while the app is running.
With polling, the IP may change without problems, because your app will ask.
Webhook may work in local, but you'll anyway need a domain and/or a static IP, I suppose.

**Comment by saeedhei** [comment]
You could use ngrok if you just needed a quick public URL to your webapp without a bunch of hassle.

So you'd just run something like `ngrok.exe http 192.168.10.10:80 -host-header=test.app` it'll return a custom domain

```Forwarding                    http://449ee26d.ngrok.io -> 192.168.10.10:80```

And you just point Telegram's webhook to `http://449ee26d.ngrok.io/your-endpoint`

[ngrok][1]


  [1]: https://ngrok.com/
