### ISSUE TITLE
Stop .on or .onText when enter the first match

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#483]
Hi,

if a user write /start on my bot, so:

```
bot.on('message', function (message) {
    if (message.from.username == "username_not_allowed"){
        // command to stop here instead of bot.onText(/^\/start,....
        // exit, return, stop, kill, what?
    }
    // else continue and match with /start...
});

bot.onText(/^\/start, function (message) {
    bot.sendMessage(...)
});
```

There is a way to stop execution instead of continue and match with next onText?

Thanks!

**Comment by xbIm** [comment]
https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md
there is an option there onlyFirstMatch

**Comment by chitkiu** [comment]
> there is an option there onlyFirstMatch
And how it use?

**Comment by sidelux** [comment]
But i need a different thing, stop ONLY in specific if or situation.
For example authentication, user write his password then every function work, without write same code in every function.

**Comment by 0xherman** [comment]
Maybe there's a better way, but I was able to get around this by setting message text null on 'message' event which stops at least onText events after:
```JavaScript
bot.on('message', (message) => {
    if (false) {
        message.text = null;
    }
    // Otherwise continue propagation
});
```

But since `on('message')` is emitted and then `message.text` onText is checked, this won't handle any async checks if you want to continue. To handle this I ended up setting `message.text` null immediately, checking if I want to send, and then essentially recreating the api code to pass message to onText which handled most of my cases. I did have to add a special check on callback query.
