### ISSUE TITLE
How can bot catch messages edited?

### ISSUE THREAD

**Issue by mykelopez** [yagop/node-telegram-bot-api#538]
How can the bot listens to a message edited?

This doesn't catch edited messages...

telegram.on("text", (message) => { 

});

**Comment by sidelux** [comment]
https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/README.md#events

"TelegramBot emits edited_message when a message is edited, and also edited_message_text or edited_message_caption depending on which type of message was edited"

So, message.edited_message IF is an edited message. Otherwise is undefined.
You can use this line to see it.
`console.log(message.edited_message);`
