### ISSUE TITLE
there is a failed connection from my server

### ISSUE THREAD

**Issue by jjhesk** [yagop/node-telegram-bot-api#549]
Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/xxxxxxxxx/getUpdates?offset=0&limit=15&timeout=5 failed, reason: connect ETIMEDOUT 69.63.184.142:443

Is there a way to use vpn to avoid bypass facebook ip?

**Comment by inkydragon** [comment]
@jjhesk You may choose a better DNS server frist. Because of the Wall, you know, you can't get the right IP, they're all redirct to facebook' IP which is totally wrong. Then, you need to go throught the Wall. 

Something may be helpful: From https://ipinfo.io/AS62041 we colud know that the right IP of telegram api should  be start with 91.108.xxx.xxx, 149.154.xxx.xxx or 2001:67c:4e8::

By the way, if you don't use webhook, using ipv6 only is a good way to avoid this situation.
