### ISSUE TITLE
Long polling is sometimes slow

### ISSUE THREAD

**Issue by nimah79** [yagop/node-telegram-bot-api#610]
I've created a bot and I use long polling, but sometimes the bot answers slowly.
How can I fix that?

**Comment by alexandercerutti** [comment]
Using polling means that the application you created has to send a request to telegram server to see if new `Update`s are available. There may be two problems there: the connection that your bot uses is slow or the settings of your bot.
Can you show us your configuration? I mean the options you passes to instance creation ( `new TelegramBot(tokenID, options)` )

**Comment by ShibinCo** [comment]
@nimah79 I also face the same issue.
@alexandercerutti  Did it still takes the time when we switch it to webhooks ?

**Comment by alexandercerutti** [comment]
Well, technically, if you switch to using a webhook the response time should depend only on the availability of your bot on the hosting (internet connection included) to receive and answering to the Update and yours to receive the reply from the bot.
The only thing you can do is trying.

**Comment by thexbasic** [comment]
I've also heard the Telegram API supports In-Request-Responses... so that techhincally the bot would work as API just returning the messages it "responds" to, instead of individually sending a extra "send" request to the telegram bot API... this should also be alot faster, but I guess you'd have to change the code architecture quite alot for that
