### ISSUE TITLE
Javascript features work on localhost but not when deployed to Heroku - node.js

### ISSUE THREAD

**Issue by saeedhei** [yagop/node-telegram-bot-api#661]
I'm running a node-telegram-bot-api via node.js in Heroku

I will want to true a false value and is ok in local, But not work in heroku.
How Should I fix?
```js
//step 1
let p = false;
//step  2
bot.onText(/\/book/, (msg) => {
  bot.sendMessage(msg.chat.id, 'This is your Book'); // ok
//step  3
  p = true; // not work in Heroku and still is false, But in local is ok and is true
});

// step  4 
bot.on('message', (msg) => {
if (p === true) {
  bot.sendMessage(msg.chat.id, p); // p is still false  
}
});
```
I want to send message only when my condition is true.

**Comment by sidelux** [comment]
Try with **var** instead of **let**, maybe in Heroku is installed different version of js.

**Comment by DtCarrot** [comment]
You can try running "heroku logs" on your terminal to find out the issue with your heroku deployment.

**Comment by saeedhei** [comment]
@sidelux I tried and did not work.
@DtCarrot No Error in "heroku logs"

**Comment by olshansky** [comment]
Do u add `engines` part in `your package.json`?
Maybe it could fix your issue 
```
"engines" : { 
  "node" : "<YOUR_LOCAL_NODE_VERSION_HERE>"
}
```

**Comment by alexandercerutti** [comment]
I think "true" assigning happens after the check because step 4 may happen before or along with step 3.
My logic reasoning is the following:
- Bot receives (or fetch) an Update structure.
- The structure is parsed and checked against some properties through EventEmitter.
- One of them is "message" because it contains a key called so.
- Therefore the message event is triggered and the variable is still false.
- Then check for Regex-matching is done
- If matches, the function is executed and the variable is set to true.

This is the part of the code responsible for the behaviour.


![image](https://user-images.githubusercontent.com/5442545/47608126-84b88680-da29-11e8-8093-dc057f1d6f03.png)

The weird thing is that that chunk of code works in local, not that doesn't work on Heroku.
Moreover, as shown, this is not the best way to achieve what you want to obtain.

1) Global vars shouldn't be used except for specific cases
2) You are working with Asyncronous operations.

I think you shouldn't use also a listener on `message`.

```javascript
bot.onText(/\/book/, (message) => {
    bot.sendMessage(msg.chat.id, 'This is your Book').then(function() {
        // do anything else.
    });
});
```

**Comment by saeedhei** [comment]
Thanks I will check 2 days later, @alexandercerutti step 4 happen after /book command, Because in bot on message has a if condition.
