### ISSUE TITLE
Dockerizing Telegram Bot

### ISSUE THREAD

**Issue by NatalieChin80** [yagop/node-telegram-bot-api#682]
# Question 

In order to dockerize the telegram bot, I have to define which port I want to expose. But the telegram docs don't specify what port polling uses. Has anyone successfully dockerized it?

**Comment by alexandercerutti** [comment]
I don't think exposing a port is needed for polling. In polling, telegram only answers to your requests. In webhook, instead, telegram sends you updates, so there you need to expose port 443 (HTTPs).

**Comment by dzek69** [comment]
I run around 6 dockerized bots on `node-telegram-bot-api` right now. All on polling right now. You don't need to expose anything. 

Polling means your script opens a normal http request to Telegram servers and that connection never ends. It has no connection timeout (should have data timeout though, after which it reconnects). Telegram servers just "sleeps" on your connection and when something happens - it just flush that information into opened connection. When you're sending messages to Telegram servers - another http connection opens up, sends the data and closes.

This isn't most performent way to do things, but it's the easiest one, because... you don't have to expose any ports or manage a http server :)

**Comment by nickglu86** [comment]
Hi,
Have the Port issue same issue.
Managing to build and ship locally, but when trying to deploy to 'back4app' getting error "Either dockerfile must expose tcp port or define port in settings".

Already tried to expose 433 and it didn't worked out  and the deploy stuck printing those lines:

- deploy stuck at trying to hit the 433 port using http
-it looks that no process is listening to the 433 port using http
-trying again in 11s

 can you assist?
