### ISSUE TITLE
Polling error after sending something that it's not text

### ISSUE THREAD

**Issue by xoko14** [yagop/node-telegram-bot-api#690]
The bot works fine when I send text or emojis. Do I have to configure something?

**Comment by kamikazechaser** [comment]
Post the error please, it may be something simple.

**Comment by xoko14** [comment]
> Post the error please, it may be something simple.

What do you mean? I'm new to github

**Comment by alexandercerutti** [comment]
Why you opened an issue? Because you have a problem, right? Well, to a problem an error is ofter associated. We need to understand what you are trying to do to help you. Please, post here the error associated to the problem and, along with your code, please provide some tests cases (I mean, what is "non-text"?). Thank you.

**Comment by xoko14** [comment]
Ok, I first ran the code and verifed that it works. Then I sent a sticker to the bot and this shows on terminal:
`error: [polling_error] {}`
The same happens if i send an image or a gif. Do I have to set up something on the code?

**Comment by alexandercerutti** [comment]
Okay. Add to your code the following chunk:

```javascript
bot.on("polling_error", (err) => console.log(err));
```

This will show more details about the problems of your code.

**Comment by alexandercerutti** [comment]
Yeah okay. So, a message is a generic entity. You should check before executing anything you want, if it has specific fields, like `msg.text`. In fact, if you send a message with a sticker, it will crash because no text is found.

To avoid any execution if no text is found, edit your conditional to the following one.

```javascript
if (msg.text && msg.text.toString().toLowerCase().includes("olvidé")) {
// ...
}
```

**Comment by xoko14** [comment]
Thanks a lot, it worked.

**Comment by alexandercerutti** [comment]
Anyway, since `msg.text` is already a text, you don't need to include `.toString()`. 😉

Please, close this issue since this has been solved.
