### ISSUE TITLE
Question (WELCOME MESSAGE) : dont get a message when users join to chat or left from

### ISSUE THREAD

**Issue by hwapedro** [yagop/node-telegram-bot-api#695]

**Comment by alexandercerutti** [comment]
Hi @hwapedro! Can you describe better your problem? And can you show us your code?

**Comment by hwapedro** [comment]
hi @alexandercerutti . I had tried to make welcome fich for bot , but i  faced with problem. i cant get message what user join to chat or leave from chat.

```
bot.on("text", async function(msg) {
  
  console.log(msg);
  const messageChatId = msg.chat.id; // chat's id
  const messageUserId = msg.from.id; // user's id
  const adminName = msg.from.username;
  const userNameId = msg.from.username;

  if (msg.new_chat_members !== undefined) {
    if (msg.new_chat_member.id !== undefined) {
      let newUserName = msg.new_chat_member.username;
      bot
      .sendMessage(
        messageChatId,
        "Hi @" + newUserName + ", thanks for joining our community!"
      )
      .then(function(data) {
        setTimeout(function() {
          bot.deleteMessage(data.chat.id, data.message_id);
        }, 500);
      });
    } else {
      let newUserName = msg.new_chat_member.first_name;
      bot
      .sendMessage(
        messageChatId,
        "Hi @" + newUserName + ", thanks for joining our community!"
      )
      .then(function(data) {
        setTimeout(function() {
          bot.deleteMessage(data.chat.id, data.message_id);
        }, 500);
      });
    }

  }
```

**Comment by alexandercerutti** [comment]
There are some events you can use to detect particular events.
Look at them here: [/doc/usage.md](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md).

You can use them as:

```javascript 
bot.on("event-name", function(msg) {
    // do something on this event
});
```

For you, events `new_chat_members` and `left_chat_member` are available to be used. There is no need to detect them manually; moreover I think you cannot do that because every [Update](https://core.telegram.org/bots/api#update) get parsed before emitting the events. Look at [Line 578 of telegram.js](https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L578)

**Comment by hwapedro** [comment]
thx, i got that
