### ISSUE TITLE
on('message') issue

### ISSUE THREAD

**Issue by velthune** [yagop/node-telegram-bot-api#71]
Hi, I'm using your code just to test my bot, and thanks for this!

Btw in method:

    bot.on('message', function (msg) { ... }

arrives text message only, have you any idea?

**Comment by GochoMugo** [comment]
The `message` event is triggered for [New incoming message of any kind — text, photo, sticker, etc.](https://core.telegram.org/bots/api#update). The handler is passed a [Message](https://core.telegram.org/bots/api#message) object.

If closing this issue is premature to you, please feel free to reopen it with more elaborate details e.g. what you were expecting and what is actually happening.

Thanks.
