### ISSUE TITLE
Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org api.telegram.org:443

### ISSUE THREAD

**Issue by andinuraziz** [yagop/node-telegram-bot-api#793]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by kamikazechaser** [comment]
Your conenction is being blocked. Some countries have been geo-restricted from using Telegram. try using a proxy.

**Comment by saeedhei** [comment]
The error message "getaddrinfo EAI_AGAIN api.telegram.org" indicates that there's a DNS resolution issue when trying to connect to the `api.telegram.org` domain. This error typically occurs when your server is having trouble resolving domain names to IP addresses.

Here are some steps you can take to troubleshoot and potentially fix this issue:

1. **Check Network Connection**: Make sure your server has a stable and working internet connection. Ensure that your server can reach external resources on the internet.

2. **DNS Configuration**: Verify your server's DNS configuration. Ensure that your DNS server settings are correctly configured and that your server can resolve domain names. You can test DNS resolution using the `nslookup` or `dig` commands.

3. **DNS Cache**: Clear your server's DNS cache to refresh the cached DNS records. The process for clearing DNS cache may vary based on your server's operating system.

   - For Linux:
     ```bash
     sudo systemctl restart systemd-resolved
     ```
   - For Windows:
     ```bash
     ipconfig /flushdns
     ```

4. **Network Firewall**: Check if there's a firewall or security software blocking outgoing connections from your server. Make sure that the necessary ports (such as port 443 for HTTPS) are open and allowed.

5. **API Endpoint Issues**: Occasionally, the Telegram API servers may experience downtime or connectivity issues. You can check Telegram's official status page or their developer documentation for any reported outages or issues.

6. **Temporary Network Issues**: Sometimes, DNS resolution errors can occur due to temporary network issues. If the issue persists, wait for a while and try again later.

7. **Use Different DNS Servers**: Consider using alternative DNS servers, such as public DNS servers provided by Google (8.8.8.8 and 8.8.4.4) or Cloudflare (1.1.1.1).

8. **Restart Server**: As a last resort, you can try restarting your server to see if the issue resolves itself.

If none of these steps resolve the issue, you may need to contact your server hosting provider or network administrator for further assistance in diagnosing and fixing the DNS resolution problem.
