### ISSUE TITLE
Telegram bot | how i can get callback from keyboard | node

### ISSUE THREAD

**Issue by AlloYEx** [yagop/node-telegram-bot-api#861]
```js
const TelegramBot = require('node-telegram-bot-api');

const token = ' ';

const bot = new TelegramBot(token, {polling: true});

const options = {
  reply_markup: {
    keyboard: [
      [{ text: 'View lesson schedule', callback_data: 'lesson' }],
      [{ text: 'View call schedule', callback_data: 'rings' }]
    ]
  }
};


bot.onText(/\/start/, (msg) => {
  const chatId = msg.chat.id;
  bot.sendMessage(chatId, 'Hello, what are you looking for?', options);
});

bot.on("callback_query", (msg) => {
  if(msg.data == "rings"){
    bot.sendPhoto(msg.chat.id, "rasp.jpg", options);
  }
});
```
Hello. I can't get data from button. How i can get callback? Thank you

**Comment by gistrec** [comment]
I just tried your code - it works.
Did you print `msg` variable?

**Comment by gistrec** [comment]
You can't handle `callback_query` via KeyboardButton.  
You have to use InlineKeyboardButton.

**Comment by ddavlet** [comment]
As @gistrec mentioned, you can't
Instead you can handle keyboard text as an ordinary 'message' type.  One of many other examples can be:

```javascript
bot.on('message`, msg => {
    if (msg.text == "View call schedule") {
         bot.sendPhoto(msg.chat.id, "rasp.jpg", options);
    }
});
```

**Comment by AbhijithNT** [comment]
https://github.com/yagop/node-telegram-bot-api/blob/5cc6629ca02c5160424be4615b281866fb56c027/examples/polling.js#L78-L84

**Comment by Mustkeem324** [comment]
It looks like you're trying to create a Telegram bot using `node-telegram-bot-api` and encountering an issue with handling callback data from buttons. The issue lies in how you're handling the `callback_query` event.

Here's a corrected version of your code to properly handle the callback data:

```javascript
const TelegramBot = require('node-telegram-bot-api');

const token = 'YOUR_TELEGRAM_BOT_TOKEN'; // Replace with your actual bot token
const bot = new TelegramBot(token, { polling: true });

const options = {
  reply_markup: {
    keyboard: [
      [{ text: 'View lesson schedule', callback_data: 'lesson' }],
      [{ text: 'View call schedule', callback_data: 'rings' }]
    ]
  }
};

// Start command handler
bot.onText(/\/start/, (msg) => {
  const chatId = msg.chat.id;
  bot.sendMessage(chatId, 'Hello, what are you looking for?', options);
});

// Callback query handler
bot.on('callback_query', (query) => {
  const chatId = query.message.chat.id;
  const data = query.data;

  if (data === 'lesson') {
    // Handle 'lesson' callback data
    bot.sendMessage(chatId, 'Here is the lesson schedule.');
  } else if (data === 'rings') {
    // Handle 'rings' callback data
    bot.sendPhoto(chatId, 'rasp.jpg', { caption: 'Here is the call schedule.' });
  }
});
```

### Explanation:
1. **Token and Bot Initialization**: Make sure you replace `'YOUR_TELEGRAM_BOT_TOKEN'` with your actual bot token obtained from BotFather.

2. **Options for Keyboard**: You've correctly defined `options` with a keyboard layout.

3. **Handling `/start` Command**: When a user sends `/start`, it sends a message with the keyboard options.

4. **Handling `callback_query`**: The `callback_query` event provides `query` object which contains `data` property. This `data` property holds the callback data associated with the button that was clicked.

5. **Conditional Handling**: Depending on the `data` received (`lesson` or `rings`), appropriate actions are taken. In your case, sending a message or sending a photo with a caption.

Make sure your bot has permission to send photos (`sendPhoto` method) and that the `rasp.jpg` file exists in your working directory or provide the correct path to the image.

By following these steps, your bot should now properly handle callback data from buttons in Telegram.
