### ISSUE TITLE
How to mention user in message?

### ISSUE THREAD

**Issue by robertnicjoo** [yagop/node-telegram-bot-api#869]
I want to have message like `Welcome @username` I've tried this `var mention = "[" + firstName + "](tg://user?id=" + str(newUserId) + ")"` but it returned error `error: [polling_error] {}`

```javascript
var mention = "[" + firstName + "](tg://user?id=" + str(newUserId) + ")"
bot.sendMessage(chatId, "Welcome " + mention);
```

**Comment by Seventty** [comment]
I could'nt tell you the reason for the error, since you do not specify how the complete error log is. What I can do is help providing you a code snippet for such events like welcome and farewells.

```javascript
bot.on('message', function(msg){
    var chatId = msg.chat.id;
    var chatitle = msg.chat.title;
    if (msg.new_chat_members != undefined){
        var nameNewMember = msg.new_chat_member.first_name;
        bot.sendMessage(chatId, "Hi  " + nameNewMember + ", Welcome to te jungle" + chatitle);
    }
    else if (msg.left_chat_member != undefined){
        var nameLeftMember = msg.left_chat_member.first_name;
        bot.sendMessage(chatId, nameLeftMember + " Bye bye")
    }
});
```

The property that contains the username of the user is in **msg.new_chat_member.username** and **msg.left_chat_member.username** **but** remember, username isnt always available because some users dont set it in them acounts. (In case the new user does'nt have a username, it will return undefined)

**Comment by robertnicjoo** [comment]
@Seventty  thanks I've solved it by this code

```javascript
var mention = `<a href="tg://user?id=${newUserId}">@${firstName}</a>`;
```
