### ISSUE TITLE
How change layer api?

### ISSUE THREAD

**Issue by Tellarion** [yagop/node-telegram-bot-api#948]
https://core.telegram.org/api/layers

Hello everyone, one question

How i can use another layer API?

Interesting sendReaction methods. (it method needed 136 level) (default 133 set)
![image](https://user-images.githubusercontent.com/23682610/156423203-5ef74dff-6e9b-433c-baca-c03a3875a725.png)

https://core.telegram.org/contest/android-2021-11-api-v2

**Comment by etroynov** [comment]
@[GochoMugo](https://github.com/GochoMugo)

**Comment by danielperez9430** [comment]
Hi @Tellarion, the layers are not from the bots API. These layers are implemented by Telegram for its PC/Android/ client.... (General API, not the bots API).

In Telegram you have on the one hand the core (the core to create Telegram client - apps) and on the other hand the bots. Therefore, in the bots layer you cannot change the layer, since if that method does not exists in the docs you can't use it.

In the following links you can see the methods and functions currently offered by the bots API:
https://core.telegram.org/bots/api
