### ISSUE TITLE
Telegram-bot-polling error

### ISSUE THREAD

**Issue by thanu159** [yagop/node-telegram-bot-api#955]
Bot works fine for first few instances. And later this error is thrown, bot stops working. 

error: [polling_error] {"code":"EFATAL","message":"EFATAL: Telegram Bot Token not provided!"}.....infinitely

tried executing :     bot.on("polling_error", (msg) => console.log(msg));
but no response

**Comment by Levelleor** [comment]
Same thing here. Also related issue: https://github.com/yagop/node-telegram-bot-api/issues/868

I don't think this is getting fixed anytime soon since this issue lacks attention for few years already.

**Comment by danielperez9430** [comment]
Umm, interesting. But the question is: Why do you launch multiple instances of the bot using Polling? If you are going to create several instances it is best to use the webhook to receive updates. Because with the polling you can only have one instance running at a time, in case you have several raised at the same time is when the error jumps the error connection.

Because in the end each instance is making requests to the Tg servers at the same time and creates a competition between the requests. And that's when Telegram can respond to one or another request, while the second one that arrives throws the error message.

That is why in the case of wanting to have several instances better to use webhook and then you can manually distribute your updates among your different instances.

What do you think about it?

**Comment by Gevionielly** [comment]
Re-generate the bot token in BotFather, it worked for me and I hope it helps you.
